### ISSUE TITLE
Allow queries with phantom parameter (no real parameters)

### ISSUE THREAD

**Issue by oraclown** [tellor-io/queryIdBuilder#27]
It's convention to have a phantom parameter for query types that don't have any real ones, so decoding query data is done in a uniform way in Solidity.

When trying to enter such a parameter in the query id builder, it won't let you generate the id without entering a string. Then when you enter an empty string it doesn't look right:

<img width="497" alt="Screen Shot 2022-12-20 at 7 09 10 PM" src="https://user-images.githubusercontent.com/50060792/208797555-14491b6d-875d-4e98-ae5a-209db942c952.png">
<img width="472" alt="Screen Shot 2022-12-20 at 7 16 06 PM" src="https://user-images.githubusercontent.com/50060792/208797599-bf745af8-6f05-467f-8fd9-97b97c9c09ed.png">

**Comment by oraclown** [comment]
More info in the query params section [here](https://github.com/tellor-io/dataSpecs/issues/new?assignees=&labels=&template=new_query_type.yaml&title=%5BNew+Query+Type%5D%3A+)

**Comment by RaynHarr** [comment]
Ok, so the fix would be to allow blank argument values in order to generate ids? That sound right?

**Comment by oraclown** [comment]
> Ok, so the fix would be to allow blank argument values in order to generate ids? That sound right?

Sounds right
